[package]
name = "ladder-rs-persistence"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Database access layer for ladder-rs"

[dependencies]
ladder-rs = { path = ".." }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tokio.workspace = true
sqlx.workspace = true
uuid.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
sqlx = { workspace = true, features = ["migrate", "runtime-tokio-rustls", "sqlite", "chrono"] }
futures = "0.3"
scopeguard = "1.2"
